import './global.css';

export const metadata = {
  title: 'Welcome to dashboard',
  description: 'Generated by create-nx-workspace',
};

import { Toaster } from 'sonner';
import AiChatInterface from '../components/AiChatInterface';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body className="bg-gray-50 min-h-screen">
        <main className="max-w-7xl mx-auto p-6">
          {children}
        </main>
        <AiChatInterface />
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
